# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Make port 8084 available to the world outside this container
EXPOSE 8084

# Run main.py and test_main.py when the container launches
CMD ["python3", "main.py"]
CMD ["python3", "test_main.py"]